-- Execute como SYS ou usuário com privilégio DBA (ajuste senha e tablespace)
CREATE USER LIFEPET IDENTIFIED BY lifepet123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO LIFEPET;
GRANT CREATE VIEW TO LIFEPET;
GRANT UNLIMITED TABLESPACE TO LIFEPET;
