-- Dados de teste para LifePet (rode no SQL Developer conectado como RM564857)
-- Ordem: Tutor -> Pet -> demais tabelas

INSERT INTO TUTORES (NOME, EMAIL, TELEFONE)
VALUES ('Maria Silva', 'maria@teste.com', '11999999999');

INSERT INTO PETS (NOME, ESPECIE, RACA, DATA_NASCIMENTO, TUTOR_ID)
VALUES ('Thor', 'Cão', 'Labrador', TIMESTAMP '2020-05-10 00:00:00', 1);

INSERT INTO VACINAS (NOME, DATA_APLICACAO, DATA_PROXIMA_DOSE, PET_ID)
VALUES ('V10', TIMESTAMP '2025-01-10 00:00:00', TIMESTAMP '2024-01-01 00:00:00', 1);

INSERT INTO CONSULTAS (DATA_HORA, VETERINARIO, MOTIVO, PET_ID)
VALUES (TIMESTAMP '2026-12-01 14:00:00', 'Dr. João', 'Check-up anual', 1);

INSERT INTO MEDICAMENTOS (NOME, DOSAGEM, FREQUENCIA, DATA_INICIO, DATA_FIM, PET_ID)
VALUES ('Antipulgas', '1 comprimido', 'Mensal', TIMESTAMP '2026-05-01 00:00:00', NULL, 1);

INSERT INTO HISTORICOS (DATA, DESCRICAO, TIPO, PET_ID)
VALUES (TIMESTAMP '2026-05-01 00:00:00', 'Exame de sangue — resultado normal', 'Exame', 1);

COMMIT;

-- Conferir:
SELECT * FROM TUTORES;
SELECT * FROM PETS;
SELECT * FROM VACINAS;
SELECT * FROM CONSULTAS;
SELECT * FROM MEDICAMENTOS;
SELECT * FROM HISTORICOS;
